### ISSUE TITLE
Can't reference item in hash

### ISSUE THREAD

**Issue by cameronjroe** [leizongmin/tinyliquid#38]
I have a yaml config with some items.

```
timeline:
  - year: 2003
    title: Founded
    content: >
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
  - year: 2004
    title: Launched Scoreboard
    content: >
      Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.
```

When I try to reference an item `timeline[1]` it's not giving me a value. Any ideas?
